# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build
FROM node:lts-alpine AS builder
WORKDIR /app

# Install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Install dependencies without running prepare/build
COPY package.json pnpm-lock.yaml tsconfig.json ./
RUN pnpm install --frozen-lockfile --ignore-scripts

# Copy source and build
COPY src ./src
COPY README.md ./README.md
RUN pnpm run build

# Stage 2: Runtime
FROM node:lts-alpine AS runtime
WORKDIR /app

# Install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Install production dependencies without running prepare/build
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --prod --ignore-scripts

# Copy built files
COPY --from=builder /app/build ./build

# Use stdio for MCP
ENTRYPOINT ["node", "build/index.js"]
